/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    Welcome: typeof import('./../src/components/Welcome/Welcome.vue')['default']
  }
}
